- project:
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py35
        - legacy-tempest-aio-ml2:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py35
        - legacy-tempest-aio-ml2:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    full:
      jobs:
        - legacy-tempest-aio-full:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    agent:
      jobs:
        - legacy-tempest-aio-agent:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    sriov:
      jobs:
        - legacy-tempest-aio-sriov:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
        - legacy-tempest-aio-sriov-allow-existing-flat-vlan:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$

    switchdev:
      jobs:
        - legacy-tempest-aio-switchdev:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
