- project:
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py35
        - legacy-tempest-aio-ml2:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
        - legacy-tempest-aio-agent:
            voting: false
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py35
        - legacy-tempest-aio-ml2:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    experimental:
      jobs:
        - legacy-tempest-aio-full:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
