#!/bin/bash

# Copyright 2015 Alcatel-Lucent USA Inc.
#
# All Rights Reserved
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

enable_service tempest
enable_service nuagetempest

NUAGE_TEMPEST_DIR=${NUAGE_TEMPEST_DIR:=$DEST/nuage-tempest-plugin}

# Nuage VSP related settings
NUAGE_VSD_SERVERS=${NUAGE_VSD_SERVERS:-'localhost:8443'}
NUAGE_VSD_SERVER_AUTH=${NUAGE_VSD_SERVER_AUTH:-'username:password'}
NUAGE_VSD_ORGANIZATION=${NUAGE_VSD_ORGANIZATION:-'org'}
NUAGE_VSD_SERVER_SSL=${NUAGE_VSD_SERVER_SSL:-'True'}
NUAGE_VSD_BASE_URI=${NUAGE_VSD_BASE_URI:-'/'}
NUAGE_VSD_AUTH_RESOURCE=${NUAGE_VSD_AUTH_RESOURCE:-'/'}
NUAGE_VSD_DEF_NETPART_NAME=${NUAGE_VSD_DEF_NETPART_NAME:-''}
NUAGE_VSD_CMS_ID=${NUAGE_VSD_CMS_ID:-''}

# SUT related settings
NUAGE_OPENSTACK_RELEASE=${NUAGE_OPENSTACK_RELEASE:-'kilo'}
NUAGE_CONTROLLER_USER=${NUAGE_CONTROLLER_USER:-'root'}
NUAGE_CONTROLLER_PSSWD=${NUAGE_CONTROLLER_PSSWD:-'password'}
NEUTRON_DB_USERNAME=${NEUTRON_DB_USERNAME:-'root'}
NEUTRON_DB_PASSWORD=${NEUTRON_DB_PASSWORD:-'secretmysql'}
NUAGE_VSP_RELEASE=${NUAGE_VSP_RELEASE:-'0.0'}
NUAGE_PLUGIN_MODE=${NUAGE_PLUGIN_MODE:-'monolithic'}
NUAGE_CONTROLLER_NODE=${NUAGE_CONTROLLER_NODE:-'devstack'}
NUAGE_PLUGIN_CONFIGURATION=${NUAGE_PLUGIN_CONFIGURATION:-'etc/neutron/plugins/nuage/nuage_plugin.ini'}
