- hosts: tempest
  become: true
  vars:
    devstack_base_dir: '/opt/stack'
  roles:
    - role: fetch-subunit-output-nuage
      zuul_work_dir: '{{ devstack_base_dir }}/tempest'
  environment: '{{ proxy_env | default({}) }}'
