- hosts: localhost
  roles:
    - role: set-nuage-vsp-facts

- hosts: all
  roles:
    - vsp-info
    - retry-binaries
  tasks:
    - name: Uninstall py2 tox
      command: python2 -m pip uninstall tox -y
      become: yes
      failed_when: false

    # gridinv: 15.1.0 causes tempest install to fail
    - name: bump virtualenv to 16.7.10
      lineinfile:
        path: /opt/stack/requirements/upper-constraints.txt
        regexp: '^virtualenv==='
        line: 'virtualenv===16.7.10'
      when: zuul.branch | regex_search("^(5.4|6.0|stable)/queens$")

    - name: Make sure 'wheel' group exists
      become: yes
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add tempest user to wheel group
      become: yes
      user: name=tempest groups=wheel append=yes state=present createhome=yes
  environment: '{{ proxy_env | default({}) }}'
