- hosts: all
  tasks:
    - name: Upgrade pip
      become: yes
      command: pip3 install --upgrade pip
    - name: Install pyOpenSSL
      become: yes
      pip:
        name: pyOpenSSL
    - name: Uninstall tox
      become: yes
      pip:
        name: tox
        state: absent
    - name: Install tox with pip3
      become: yes
      pip:
        name: tox
        state: present
        executable: pip3
  environment: '{{ proxy_env }}'
